from flask import Flask, render_template
import random

app = Flask(__name__)

# Defining list of countries and their names
countries = [
    {"name": "Afganistan", "flag": "static/Afganistan.png"},
    {"name": "Albania", "flag": "static/Albania.png" },
    {"name": "Algeria", "flag": "static/Algeria.png"},
    {"name": "Andora", "flag": "static/Andora.png"},
    {"name": "Angola", "flag": "static/Angola.png"},
    {"name": "Antigua and Barbuda", "flag": "static/Antigua and Barbuda.png"},
    {"name": "Argentina", "flag": "static/Argentina.png"},
    {"name": "Armenia", "flag": "static/Armenia.png"},
    {"name": "Australia", "flag": "static/Australia.png"},
    {"name": "Austria", "flag": "static/Austria.png"},
    {"name": "Azerbaijan", "flag": "static/Azerbaijan.png"},
    {"name": "The Bahamas", "flag": "static/The Bahamas.png"},
    {"name": "Bahrain", "flag": "static/Bahrain.png"},
    {"name": "Bangladesh", "flag": "static/Bangladesh.png"},
    {"name": "Barbados", "flag": "static/Barbados.png"},
    {"name": "Belarus", "flag": "static/Belarus.png"},
    {"name": "Belgium", "flag": "static/Belgium.png"},
    {"name": "Belize", "flag": "static/Belize.png"},
    {"name": "Benin", "flag": "static/Benin.png"},
    {"name": "Bhutan", "flag": "static/Bhutan.png"},
    {"name": "Bolivia", "flag": "static/Bolivia.png"},
    {"name": "Bosnia and Herzegovina", "flag": "static/Bosnia and Herzegovina.png"},
    {"name": "Botswana", "flag": "static/Botswana.png"},
    {"name": "Brazil", "flag": "static/Brazil.png"},
    {"name": "Brunei", "flag": "static/Brunei.png"},
    {"name": "Bulgaria", "flag": "static/Bulgaria.png"},
    {"name": "Burkina Faso", "flag": "static/Burkina Faso.png"},
    {"name": "Burundi", "flag": "static/Burnundi.png"},
    {"name": "Cabo Verde (Cape Verde)", "flag": "static/Cabo Verde.png"},
    {"name": "Cambodia", "flag": "static/Cambodia.png"},
    {"name": "Cameroon", "flag": "static/Cameroon.png"},
    {"name": "Canada", "flag": "static/Canada.png"},
    {"name": "Central African Republic", "flag": "static/Central African Republic.png"},
    {"name": "Chad", "flag": "static/Chad.png"},
    {"name": "Chile", "flag": "static/Chile.png"},
    {"name": "China", "flag": "static/China.png"},
    {"name": "Colombia", "flag": "static/Colombia.png"},
    {"name": "Comoros", "flag": "static/Comoros.png"},
    {"name": "Democratic Republic of the Congo", "flag": "static/Democratic Republic of the Congo.png"},
    {"name": "Republic of the Congo", "flag": "static/Republic of the Congo.png"},
    {"name": "Costa Rica", "flag": "static/Costa Rica.png"},
    {"name": "Côte d'Ivoire", "flag": "static/Côte d'Ivoire.png"},
    {"name": "Croatia", "flag": "static/Croatia.png"},
    {"name": "Cuba", "flag": "static/Cuba.png"},
    {"name": "Cyprus", "flag": "static/Cyprus.png"},
    {"name": "Czech Republic", "flag": "static/Czech Republic.png"},
    {"name": "Denmark", "flag": "static/Denmark.png"},
    {"name": "Djibouti", "flag": "static/Djibouti.png"},
    {"name": "Dominica", "flag": "static/Dominica.png"},
    {"name": "Dominican Republic", "flag": "static/Dominican Republic.png"},
    {"name": "East Timor", "flag": "static/East Timor.png"},
    {"name": "Ecuador", "flag": "static/Ecuador.png"},
    {"name": "Egypt", "flag": "static/Egypt.png"},
    {"name": "El Salvador", "flag": "static/El Salvador.png"},
    {"name": "Equatorial Guinea", "flag": "static/Equatorial Guinea.png"},
    {"name": "Eritrea", "flag": "static/Eritrea.png"},
    {"name": "Estonia", "flag": "static/Estonia.png"},
    {"name": "Eswatini (SwazilandEsw)", "flag": "static/Eswatini.png"},
    {"name": "Ethiopia", "flag": "static/Ethiopia.png"},
    {"name": "Fiji", "flag": "static/Fiji.png"},
    {"name": "Finland", "flag": "static/Finland.png"},
    {"name": "France", "flag": "static/France.png"},
    {"name": "Gabon", "flag": "static/Gabon.png"},
    {"name": "The Gambia", "flag": "static/The Gambia.png"},
    {"name": "Georgia", "flag": "static/Georgia.png"},
    {"name": "Germany", "flag": "static/Germany.png"},
    {"name": "Ghana", "flag": "static/Ghana.png"},
    {"name": "Greece", "flag": "static/Greece.png"},
    {"name": "Grenada", "flag": "static/Grenada.png"},
    {"name": "Guatemala", "flag": "static/Guatemala.png"},
    {"name": "Guinea", "flag": "static/Guinea.png"},
    {"name": "Guinea-Bissau", "flag": "static/Guinea-Bissau.png"},
    {"name": "Guyana", "flag": "static/Guyana.png"},
    {"name": "Haiti", "flag": "static/Haiti.png"},
    {"name": "Honduras", "flag": "static/Honduras.png"},
    {"name": "Hungary", "flag": "static/Hungary.png"},
    {"name": "Iceland", "flag": "static/Iceland.png"},
    {"name": "India", "flag": "static/India.png"},
    {"name": "Indonesia", "flag": "static/Indonesia.png"},
    {"name": "Iran", "flag": "static/Iran.png"},
    {"name": "Iraq", "flag": "static/Iraq.png"},
    {"name": "Ireland", "flag": "static/Ireland.png"},
    {"name": "Israel", "flag": "static/Israel.png"},
    {"name": "Italy", "flag": "static/Italy.png"},
    {"name": "Jamaica", "flag": "static/Jamaica.png"},
    {"name": "Japan", "flag": "static/Japan.png"},
    {"name": "Jordan", "flag": "flags/algeria.png"},
    {"name": "Kazakhstan", "flag": "flags/algeria.png"},
    {"name": "Kenya", "flag": "flags/algeria.png"},
    {"name": "Kiribati", "flag": "flags/algeria.png"},
    {"name": "North Korea", "flag": "flags/algeria.png"},
    {"name": "South Korea", "flag": "flags/algeria.png"},
    {"name": "Kosovo", "flag": "flags/algeria.png"},
    {"name": "Kuwait", "flag": "flags/algeria.png"},
    {"name": "Kyrgyzstan", "flag": "flags/algeria.png"},
    {"name": "Laos", "flag": "flags/algeria.png"},
    {"name": "Latvia", "flag": "flags/algeria.png"},
    {"name": "Lebanon", "flag": "flags/algeria.png"},
    {"name": "Lesotho", "flag": "flags/algeria.png"},
    {"name": "Liberia", "flag": "flags/algeria.png"},
    {"name": "Libya", "flag": "flags/algeria.png"},
    {"name": "Liechtenstein", "flag": "flags/algeria.png"},
    {"name": "Lithuania", "flag": "flags/algeria.png"},
    {"name": "Luxembourg", "flag": "flags/algeria.png"},
    {"name": "Madagascar", "flag": "flags/algeria.png"},
    {"name": "Malawi", "flag": "flags/algeria.png"},
    {"name": "Malaysia", "flag": "flags/algeria.png"},
    {"name": "Maldives", "flag": "flags/algeria.png"},
    {"name": "Mali", "flag": "flags/algeria.png"},
    {"name": "Malta", "flag": "flags/algeria.png"},
    {"name": "Marshall Islands", "flag": "flags/algeria.png"},
    {"name": "Mauritania", "flag": "flags/algeria.png"},
    {"name": "Mauritius", "flag": "flags/algeria.png"},
    {"name": "Mexico", "flag": "flags/algeria.png"},
    {"name": "Federated States of Micronesia", "flag": "flags/algeria.png"},
    {"name": "Moldova", "flag": "flags/algeria.png"},
    {"name": "Monaco", "flag": "flags/algeria.png"},
    {"name": "Mongolia", "flag": "flags/algeria.png"},
    {"name": "Montenegro", "flag": "flags/algeria.png"},
    {"name": "Morocco", "flag": "flags/algeria.png"},
    {"name": "Mozambique", "flag": "flags/algeria.png"},
    {"name": "Myanmar (Burma)", "flag": "flags/algeria.png"},
    {"name": "Namibia", "flag": "flags/algeria.png"},
    {"name": "Nauru", "flag": "flags/algeria.png"},
    {"name": "Nepal", "flag": "flags/algeria.png"},
    {"name": "Netherlands", "flag": "flags/algeria.png"},
    {"name": "New Zealand", "flag": "flags/algeria.png"},
    {"name": "Nicaragua", "flag": "flags/algeria.png"},
    {"name": "Niger", "flag": "flags/algeria.png"},
    {"name": "Nigeria", "flag": "flags/algeria.png"},
    {"name": "North Macedonia", "flag": "flags/algeria.png"},
    {"name": "Norway", "flag": "flags/algeria.png"},
    {"name": "Oman", "flag": "flags/algeria.png"},
    {"name": "Pakistan", "flag": "flags/algeria.png"},
    {"name": "Palau", "flag": "flags/algeria.png"},
    {"name": "Panama", "flag": "flags/algeria.png"},
    {"name": "Papua New Guinea", "flag": "flags/algeria.png"},
    {"name": "Paraguay", "flag": "flags/algeria.png"},
    {"name": "Peru", "flag": "flags/algeria.png"},
    {"name": "Philippines", "flag": "flags/algeria.png"},
    {"name": "Poland", "flag": "flags/algeria.png"},
    {"name": "Portugal", "flag": "flags/algeria.png"},
    {"name": "Qatar", "flag": "flags/algeria.png"},
    {"name": "Romania", "flag": "flags/algeria.png"},
    {"name": "Russia", "flag": "flags/algeria.png"},
    {"name": "Rwanda", "flag": "flags/algeria.png"},
    {"name": "Saint Kitts and Nevis", "flag": "flags/algeria.png"},
    {"name": "Saint Lucia", "flag": "flags/algeria.png"},
    {"name": "Saint Vincent and the Grenadines", "flag": "flags/algeria.png"},
    {"name": "Samoa", "flag": "flags/algeria.png"},
    {"name": "San Marino", "flag": "flags/algeria.png"},
    {"name": "Sao Tome and Principe", "flag": "flags/algeria.png"},
    {"name": "Saudi Arabia", "flag": "flags/algeria.png"},
    {"name": "Senegal", "flag": "flags/algeria.png"},
    {"name": "Serbia", "flag": "flags/algeria.png"},
    {"name": "Seychelles", "flag": "flags/algeria.png"},
    {"name": "Sierra Leone", "flag": "flags/algeria.png"},
    {"name": "Singapore", "flag": "flags/algeria.png"},
    {"name": "Slovakia", "flag": "flags/algeria.png"},
    {"name": "Slovenia", "flag": "flags/algeria.png"},
    {"name": "Solomon Islands", "flag": "flags/algeria.png"},
    {"name": "Somalia", "flag": "flags/algeria.png"},
    {"name": "South Africa", "flag": "flags/algeria.png"},
    {"name": "Spain", "flag": "flags/algeria.png"},
    {"name": "Sri Lanka", "flag": "flags/algeria.png"},
    {"name": "Sudan", "flag": "flags/algeria.png"},
    {"name": "South Sudan", "flag": "flags/algeria.png"},
    {"name": "Suriname", "flag": "flags/algeria.png"},
    {"name": "Sweden", "flag": "flags/algeria.png"},
    {"name": "Switzerland", "flag": "flags/algeria.png"},
    {"name": "Syria", "flag": "flags/algeria.png"},
    {"name": "Taiwan", "flag": "flags/algeria.png"},
    {"name": "Tajikistan", "flag": "flags/algeria.png"},
    {"name": "Tanzania", "flag": "flags/algeria.png"},
    {"name": "Thailand", "flag": "flags/algeria.png"},
    {"name": "Togo", "flag": "flags/algeria.png"},
    {"name": "Tonga", "flag": "flags/algeria.png"},
    {"name": "Trinidad and Tobago", "flag": "flags/algeria.png"},
    {"name": "Tunisia", "flag": "flags/algeria.png"},
    {"name": "Turkey", "flag": "flags/algeria.png"},
    {"name": "Turkmenistan", "flag": "flags/algeria.png"},
    {"name": "Tuvalu", "flag": "flags/algeria.png"},
    {"name": "Uganda", "flag": "flags/algeria.png"},
    {"name": "Ukraine", "flag": "flags/algeria.png"},
    {"name": "United Arab Emirates", "flag": "flags/algeria.png"},
    {"name": "United Kingdom", "flag": "flags/algeria.png"},
    {"name": "United States of America", "flag": "flags/algeria.png"},
    {"name": "Uruguay", "flag": "flags/algeria.png"},
    {"name": "Uzbekistan", "flag": "flags/algeria.png"},
    {"name": "Vanuatu", "flag": "flags/algeria.png"},
    {"name": "Vatican City", "flag": "flags/algeria.png"},
    {"name": "Venezuela", "flag": "flags/algeria.png"},
    {"name": "Vietnam", "flag": "flags/algeria.png"},
    {"name": "Yemen", "flag": "flags/algeria.png"},
    {"name": "Zambia", "flag": "flags/algeria.png"},
    {"name": "Zimbabwe", "flag": "flags/algeria.png"}
]

def generate_options(correct_option):
    # Generate options randomly with the correct option included
    options = [correct_option]

    while len(options) < 3:
        new_option = f"Option{random.randint(1, 195)}"
        if new_option not in options:
            options.append(new_option)

    # Shuffle the options so that correct option in at a random postion
    random.shuffle(options)
    return options

def get_correct_option(country_name):
    # Take the first letter of the country name as the correct answer
    return "Option" + country_name[0].upper()


@app.route('/')
def index():
    return render_template('index.html')

@app.route('/game')
def game():
    # Randomly select a country
    selected_country = random.choice(countries)

    # Generate options for the selected country
    correct_option = get_correct_option(selected_country['name'])
    selected_country['options'] = generate_options(correct_option)


    # Pass data to the template
    return render_template('game.html', country=selected_country)

if __name__ == '__main__':
    app.run(debug=True)